### ISSUE TITLE
用values或value_list方法提取想要的数据

### ISSUE THREAD

**Issue by Promisexsw** [TencentBlueKing/python-best-practices#14]
示例1：fruits_list = Fruits.objects.all()
            if fruits_list:
                          print(fruits.name)
示例2：fruits_list = Fruits.objects.values('id', 'name')
             if fruits_list:
                         print(fruits.name)
总结：虽然都是拿到了name，但是第一种示例会从数据库中提取所有字段，耗时耗力，那么第二种示例只需要拿我们想要的数据，节省了查询时间和内存。

**Comment by yiqiwang-17** [comment]
<img width="792" alt="image" src="https://user-images.githubusercontent.com/66986742/189056126-ce826301-f753-41f5-9296-d667ae302625.png">
文档中已存在该条实践总结，可以扩展其他Django最佳实践的使用。
更推荐使用Issue模板提供建议，代码段高亮可复制。
