### ISSUE TITLE
函数提供类型注解

### ISSUE THREAD

**Issue by yiqiwang-17** [TencentBlueKing/python-best-practices#9]
### 函数提供类型注解

对变量和函数的参数返回值类型做注解，有助于让调用方减少类型方面的错误。

```python
# BAD
def greeting(name):
    return 'Hello ' + name

# GOOD
def greeting(name: str) -> str:
    return 'Hello ' + name
```

##

**Comment by IMBlues** [comment]
原则上对于新项目我的建议是尽可能多的添加类型注解

之前阅读过一篇关于类型注解 + MyPy 的好处：https://notes.crmarsh.com/using-mypy-in-production-at-spring
